#!/bin/sh
echo "Running golint for staged go file"

STAGED_GO_FILES=$(git diff --cached --name-only | grep "\.go$")

if [[ "$STAGED_GO_FILES" = "" ]]; then
  echo No staged go file
fi

PASS=

for FILE in $STAGED_GO_FILES
do 
  errorCount=$(go run golang.org/x/lint/golint $STAGED_GO_FILES | wc -l)
  if [ "$errorCount" -gt '0' ]; then
    printf "\t\033[31mgolint $FILE\033[0m \033[0;30m\033[41mFAIL\033[0m\n"
      
    echo $errCount
    echo "suggestions for: $FILE"
    go run golang.org/x/lint/golint $FILE
    PASS=false
  else  
    printf "\t\033[32mgolint $FILE\033[0m \033[0;30m\033[42mPASS\033[0m\n"
    PASS=true
  fi
done

if ! $PASS; then
  printf "\033[0;30m\033[41mCOMMIT FAILED !!!!\033[0m\n"
  exit 1
else
  printf "\033[0;30m\033[42mCOMMIT SUCCEEDED\033[0m\n"
  exit 0
fi
